#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sanitize
Version  : 4.0.0
Release  : 5
URL      : ttps://rubygems.org/downloads/sanitize-4.0.0.gem
Source0  : ttps://rubygems.org/downloads/sanitize-4.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-crass
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-nokogumbo
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-redcarpet

%description
Sanitize
========
Sanitize is a whitelist-based HTML and CSS sanitizer. Given a list of acceptable
elements, attributes, and CSS properties, Sanitize will remove all unacceptable
HTML and/or CSS from a string.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sanitize-4.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-sanitize.gemspec

%build
gem build rubygem-sanitize.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sanitize-4.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/sanitize-4.0.0
ruby -v -I"lib:test" test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/sanitize-4.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/at_rule%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/cdesc-CSS.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/properties-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/properties-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/property%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/stylesheet-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/tree%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/tree%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/CSS/valid_url%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Config/can_dupe%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Config/cdesc-Config.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Config/freeze_config-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Config/merge-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanAttribute/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanAttribute/cdesc-CleanAttribute.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanAttribute/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanElement/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanElement/cdesc-CleanElement.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/CleanElement/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CSS/cdesc-CSS.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CleanElement/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CleanElement/cdesc-CleanElement.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/CleanElement/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/Transformers/cdesc-Transformers.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/cdesc-Sanitize.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean_document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean_document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean_node%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/clean_node%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/config-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/document-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/document-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/fragment-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/fragment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/node%21-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/node%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/preprocess-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/to_html-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/transform_node%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/Sanitize/traverse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sanitize-4.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/config.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/config/basic.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/config/default.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/config/relaxed.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/config/restricted.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/css.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_cdata.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_comment.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_css.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_doctype.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_element.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/lib/sanitize/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/common.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_clean_comment.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_clean_css.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_clean_doctype.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_clean_element.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_config.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_malicious_css.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_malicious_html.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_sanitize.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_sanitize_css.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_transformers.rb
/usr/lib64/ruby/gems/2.2.0/gems/sanitize-4.0.0/test/test_unicode.rb
/usr/lib64/ruby/gems/2.2.0/specifications/sanitize-4.0.0.gemspec
