#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sanitize
Version  : 4.0.0
Release  : 6
URL      : ttps://rubygems.org/downloads/sanitize-4.0.0.gem
Source0  : ttps://rubygems.org/downloads/sanitize-4.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-crass
BuildRequires : rubygem-mini_portile
BuildRequires : rubygem-minitest
BuildRequires : rubygem-nokogiri
BuildRequires : rubygem-nokogumbo
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-redcarpet

%description
Sanitize
========
Sanitize is a whitelist-based HTML and CSS sanitizer. Given a list of acceptable
elements, attributes, and CSS properties, Sanitize will remove all unacceptable
HTML and/or CSS from a string.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sanitize-4.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-sanitize.gemspec

%build
gem build rubygem-sanitize.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sanitize-4.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/sanitize-4.0.0
ruby -v -I.:lib:test test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/sanitize-4.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/config/basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/config/default.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/config/relaxed.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/config/restricted.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_cdata.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_comment.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_doctype.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/transformers/clean_element.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/lib/sanitize/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/common.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_clean_comment.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_clean_css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_clean_doctype.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_clean_element.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_config.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_malicious_css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_malicious_html.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_sanitize.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_sanitize_css.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_transformers.rb
/usr/lib64/ruby/gems/2.3.0/gems/sanitize-4.0.0/test/test_unicode.rb
/usr/lib64/ruby/gems/2.3.0/specifications/sanitize-4.0.0.gemspec
